#program to perform arithmetical operations
a=int(input("enter the first  number")
b=int(input("enter the second number")
      print("addition=",a+b)
      print("subtraction=",a-b)
      print("multiplication=",a*b)
      print("division=",a/b)
      print("modulus=",a%b)
      print("exponentiation=",a**b)
      print("floor division=",a//b)
